### ISSUE TITLE
[Spike] Analyze performance issues

### ISSUE THREAD

**Issue by philsturgeon** [stoplightio/elements#1064]
## Description

**Time limit**: one day.

Spend one day analyzing performance issues, and come up with areas of improvement. Fix the most important one if you have the time.

## To Reproduce

1. Given this demo URL https://elements-demo.stoplight.io/?spec=https://api.apis.guru/v2/specs/stripe.com/2020-08-27/openapi.yaml#/operations/Post3dSecure
2. See error

## Expected behavior

It should either load eventually (slowly but calmly) or error out and say this API document could not be loaded.

## Additional context

**Screenshot**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/67381/114863945-4c1eea00-9de8-11eb-9739-1dbbdb1c2670.png">

**Environment:**
 - Library version: f9cb301
 - OS: MacOS
 - Browser: Firefox 87

**Comment by marcelltoth** [comment]
## Summary

I investigated performance problems while loading Stripe, and other docs.

### Identified problem areas

#### Non-bundled specs

Many specs we handle (even ones on the demo page) are not bundled, meaning that the original specs files with tons of external refs are uploaded. We handle spec-relative and absolute-URL external refs just fine, but this often means needing to download 10s (or in extreme cases approaching 100) separate files from the server. This causes a very significant performance hit, especially on the first load (and on subsequent loads if HTTP caching is not configured).

*Non actionable, users can fix it for themselves.*

#### $ref parsing bottleneck

The Stripe spec is bundled, but it contains literally more than 1700 $refs, parsing and resolving this takes time. I identified some hotspots in `@stoplight/json-schema-ref-parser` which I am about to send a PR for. According to my measurements, this can shave off about 1-2s off loading all pages.

* Simple fix, will be fixed in the scope of this issue.*

#### Mosaic bottleneck with a large ToC

The Stripe spec does not use tags, so every endpoint and model is dumped directly onto the main ToC, generating some 800+ entries. As the new ToC is using mosaic's css-abstractions (`Box`, `Flex` and friends) heavily, this places a large toll (about an extra 1-2s on my machine) on rendering any page. As in JSV, replacing abstractions with their underlying (e.g. `<Box my={3} />` -> `<div className="sl-my-3"/>`) improves performance heavily.

* Simple fix, can be done later if required. *

With these implemented, the overview page now loads fairly rapidly, especially given that it's a 2.8MB spec.


### Unknowns

Unfortunately with all the above implemented, the individual operation pages of the Stripe spec are still taking a lot of time to render. This needs further investigation.
