### ISSUE TITLE
Stylesheet is not found at unpkg.com

### ISSUE THREAD

**Issue by SvenVw** [stoplightio/elements#1219]
## Describe the bug

When following the instructions for the use of Web Components according to the README, the link for the CSS: https://unpkg.com/@stoplight/elements@beta/styles/elements.min.css resolves with a 404. Making it not possible to load the stylesheet.

## To Reproduce

1. Go to https://unpkg.com/@stoplight/elements@beta/styles/elements.min.css

## Expected behavior
Should response with a 200 and the requested CSS file

**Comment by mpodlasin** [comment]
Hey!

Thanks for reporting!

Unfortunately because of an error on our part, names of styles changed - https://unpkg.com/@stoplight/elements@beta/styles/elements-core.min.css

Even more unfortunately, we plan to change name once more before the stable version release - with that next change we will make sure to update readme with proper urls.

We apologize for the inconvenience but it is a result of us trying to develop a build system that will ensure long-term stability for our users. :pray:

**Comment by mpodlasin** [comment]
Actually, let me keep that open for visibility as long as our styles are misnamed.

**Comment by philsturgeon** [comment]
Fixed in https://github.com/stoplightio/elements/pull/1253 but we'll need to tag a new beta.

**Comment by philsturgeon** [comment]
Fixed and tagged beta3.

new URL is https://unpkg.com/@stoplight/elements@beta/styles.min.css
