### ISSUE TITLE
Double values in Header

### ISSUE THREAD

**Issue by K2ouMais** [stoplightio/elements#1298]
Hello everyone,

I am having a strange behaviour while I try to "Send Request".

My API is working with Insomnia and Postman without a problem, but when I try to send a request throught the UI my middleware goes crazy and says the headers are not right.

![stoplight](https://user-images.githubusercontent.com/52510455/118952985-b59c9600-b95c-11eb-9aaf-d8f2b367e6a2.png)

It seems the header "content-type" has 2 values and that is exactly the problem with my middleware. It is looking if the value of content-type is only "application/json" and in this case it is "application/json, application/json".

**Comment by philsturgeon** [comment]
@K2ouMais can you please try and give us some of your OpenAPI when reporting bugs, because it makes it a lot easier to debug. Our bug report template asks for this, and a few other details which make solving bugs a lot easier. 

If I'm going to guess at this one, I think you have probably defined Content-Type as a header parameter manually, which you don't need to do. We attempt to merge when this happens, but for now could you try deleting the Content-Type parameter in your OpenAPI? It's redundant as it's covered by the request Media Type object.

**Comment by K2ouMais** [comment]
@philsturgeon yes, your are right. I have defined the content-type as a header. If I take it out it works everything like it should.

One other question... You said the content-type header is redundant by the request Media Type, but why is this like so?

Every endpoint that doesnt have a body shouldnt need that header. Or is just me?

I still see the content-type header in the request samples, where I dont have set a content-type header and where the endpoint dont have a body at all.

This is kinda strange to me.

Thank you.

**Comment by philsturgeon** [comment]
It's redundant in OpenAPI itself because you define the request body mime type on the request body, so there's no need to make a parameter that also does that. 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/67381/119011733-3d9a9400-b98d-11eb-898e-d5d333e48f06.png">

The same goes for Authentication, which is covered by securityScheme already.

We'll use this issue to merge them safely (which we already do for authentication), but it sounds like you're all set. Thanks for reporting.

**Comment by K2ouMais** [comment]
Thank you for your explanation.
