### ISSUE TITLE
Change react-query settings for failing requests.

### ISSUE THREAD

**Issue by mpodlasin** [stoplightio/elements#1452]
## Summary

Currently react-query tries to refetch data a few times if request fails. Sometimes that's good, but in many cases it's bad for us.

For example when users are on unpaid program and they try to load StoplightProject they have to wait very long for the info. They just see loader for a loooong time, which gives impression that the app is sluggish.

<img width="274" alt="Zrzut ekranu 2021-06-18 o 13 19 37" src="https://user-images.githubusercontent.com/7916523/122554418-3ec8ea80-d039-11eb-835a-3ee1591e9a30.png">

## Tasks

- [ ] Don't retry requests, especially ones that return 4xx

**Comment by philsturgeon** [comment]
Good spot. We definitely don’t want to retry things that don’t need to be retried. That’s bad for our servers, bad for clients device batteries, and bad for the environment.  

Is there any good auto retry logic for react based apps? 

For example, Ruby has Faraday; which knows which HTTP methods to retry, which statuses to retry, and which headers to use to modify that retry logic.

**Comment by mpodlasin** [comment]
That's the thing - it's this `react-query` library that manages fetching now, introduced in recent dev-portal PRs. 

I am sure they have some configurations options that allow to decide when and if to refetch - that's the whole purpose of that lib to manage fetching.

**Comment by philsturgeon** [comment]
Right I’m just wondering if it’s got useful HTTP-centric defaults. Generally client errors should not be retried because it’s a client error, they’re doing something wrong so why do it wrong twice? There’s exceptions to that like if you’re 403 forbidden over oauth2 using access tokens you need to refresh that token, but generally not.

A good retry middleware will know most of the normal times when it’s a good or bad idea to retry, and things like the server emitting Retry-After can help a client know which 5XX to retry, but if it’s just blindly retrying (and doesn’t have backoffs logic) then retries are actually compounding 5XX issues by DDoSing our APIs every time they struggle. If we are doing auto retry, we want backoff, and soon probably even circuit breakers. 

https://apisyouwonthate.com/blog/taking-a-timeout-from-poor-performance

Just food for thought. Of course for now doing the smaller bit of work is ideal, but general advice is always “find a smart middleware to do it and save you having to think too much”. :)

--
Phil Sturgeon
Product @ Stoplight.io

**Comment by marcelltoth** [comment]
Recategorizing as a bug as we
1. don't reliably show the failure screen
2. DDoS the user's site. (or our own, in case of StoplightProject)
