### ISSUE TITLE
Mix of yaml and MK files

### ISSUE THREAD

**Issue by UniPAYNINJA** [stoplightio/elements#1499]
Hi, I am trying to use stopligh Element with Stoplight Studio

I am creating the API , Docs and Files as well but it is not possible to generate yaml with MK file.

also its not possible to generate MK files to use for Element. 

can you guide anything on how I can combine api and mk documentation together or how to export MK file for element open source project to show the documentation

**Comment by mnaumanali94** [comment]
To use markdown and OpenAPI files together you'd want to use the elements dev portal component documented here: https://meta.stoplight.io/docs/elements/docs/getting-started/dev-portal/introduction.md

**Comment by UniPAYNINJA** [comment]
Do I need to install an open source Element project to get Element Dev portal?

**Comment by philsturgeon** [comment]
Elements Dev Portal is like an extension of Elements which does more, but is based off of having a Stoplight Project instead of just any old OpenAPI file. 

This section of the documentation explains the difference. 

https://meta.stoplight.io/docs/elements/docs/introduction.md#elements-vs-elements-dev-portal

Let me know if you have any questions!
