### ISSUE TITLE
Usage of basePath="/docs" @stoplight/elements

### ISSUE THREAD

**Issue by knkrth** [stoplightio/elements#1603]
What's the usage of `basePath="/docs"` while using `apiDescriptionUrl`?

```
<elements-api
      apiDescriptionUrl="https://api.apis.guru/v2/specs/github.com/1.1.4/openapi.yaml"
      basePath="/docs"
      router="hash"
      layout="sidebar"
    />
```

**Comment by mpodlasin** [comment]
Hi @knkrth !

`basePath` is not related to `apiDescriptionUrl`.

Because elements uses it's own router internally, in order for it to work when embedded on other websites we need to know the "base path" of where the component is being rendered.

If you render elements under the root url - `/` - then you can omit that parameter entirely. This will be often the case if you render *only* elements in your project and nothing else.

If however you are rendering elements on a subpage, for example `www.my-website.com/docs`, then you would provide `/docs` as `basePath`.

Thanks to that the component will know to use `/docs/some-article` instead of just `/some-article` url when clicking on links for example.

I hope that explains it. Let me know if you have more questions!

**Comment by knkrth** [comment]
Thanks, I can see the example here: [static-html](https://github.com/stoplightio/elements/tree/main/examples/static-html) Where `zoom-api` path is defined in [L23](https://github.com/stoplightio/elements/blob/main/examples/static-html/zoom-api/index.html#L23)
