### ISSUE TITLE
multiple examples for schemas don't show up in platform

### ISSUE THREAD

**Issue by mnaumanali94** [stoplightio/elements#1662]
Currently we don't show multiple examples for schemas

![Screenshot 2021-08-03 at 5.37.53 AM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/71aeb768-67cd-4838-bb25-8133fadb8606)

Lets convert the above to `Examples` and a dropdown like below if there are multiple examples:

![Screenshot 2021-08-03 at 5.37.49 AM.png](https://images.zenhubusercontent.com/5ea9a7f489044245dbd23d46/77d18d3a-7ed1-4c5e-aefb-b2e5eece5f19)

**Comment by mallachari** [comment]
Examples don't show in platform because they are missing. The example that is visible in Docs doesn't come from the document - it is generated. Parsed document (HttpOperation) lacks `examples` property in media object. That's probably the result of incorrectly analyzing document as it is missing in node_snapshot as well. Transform operation in `http-spec` seems fine as it does the job in Elements API component for the same document.

**Comment by domagojk** [comment]
Hm, I haven't find any issues in node_snapshot table (example was there), and I got it working by doing this https://github.com/stoplightio/elements/pull/1693
Am i missing something?
