### ISSUE TITLE
Two layer text in code editor doesn't overlapped exactly. 

### ISSUE THREAD

**Issue by iseki0** [stoplightio/elements#1940]
## Describe the bug

Two layer text in code editor doesn't overlapped exactly. (Only in Chrome browser)
## To Reproduce

1. Open any document in Chrome browser, such as [Example](https://elements-demo.stoplight.io/?_ga=2.174548962.198023653.1640187778-2134395263.1638722178#/operations/post-users-userID)
2. Select code in editor
3. See...
<img width="442" alt="image" src="https://user-images.githubusercontent.com/13687964/147123880-9cbfe2c2-8a67-4de7-aa03-e8e865816a2a.png">

## Expected behavior

Two layer text should overlapped exactly. 

## Additional context
And in Firefox browser, the problem doesn't exists (tested in Firefox Developer 96.0b7).
Tested in clean session. And edit system scale is not useful.

**Environment (remove any that are not applicable):**
 - Library version: elements@7.5.5
 - OS: Windows 10 21H1 (zh-CN)
 - Browser: Chrome 96.0.4664.110 (64 bit)
 - Platform: desktop

**Comment by mnaumanali94** [comment]
@cpdyj I can't seem to reproduce it. Can you try again and let us know if you still see it?

**Comment by cpdyj** [comment]
@mnaumanali94 Yes I can. Something I don't know if it's useful. When I focus on the `.npm__react-simple-code-editor__textarea` element. Chrome develop tool shows the rendered font is `Consolas`. But the background `pre` element doesn't.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
