### ISSUE TITLE
Links in api.yaml to other HTTP methods don't resolve in Elements or Studio (but do in Studio edit mode)

### ISSUE THREAD

**Issue by fsargent** [stoplightio/elements#2004]
## Describe the bug

Links in api.yaml to other HTTP methods don't resolve in Elements (but do in Studio)

## To Reproduce

[Our Studio docs page](https://stoplight.truework.com/docs/truework/b3A6MzMxNTc2ODA-create-a-new-verification)
[Our Elements docs page](https://www.truework.com/docs-2/b3A6MzMxNTc2ODA-create-a-new-verification#verification-processing)

The link in the text "Verifications are generally processed asynchronously: they will be created and returned in the response body without any `reports`." will not resolve properly, though it does in the "Edit" mode of Stoplight Studio.
Also fails to resolve on Stoplight Elements.

https://www.loom.com/share/310f6e7a6683494b9ab5dee47266dce3

## Expected behavior

Link is expected to resolve.

**Comment by fsargent** [comment]
@lottamus Another one for you.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
