### ISSUE TITLE
Display Operation ID

### ISSUE THREAD

**Issue by yordis** [stoplightio/elements#2007]
## User story.

As a viewer of the specification, I can do view the `operation id` of the operation, so that I can use it to find the SDK function name.

## Is your feature request related to a problem?

There is no way to see the "Operation ID" of an operation in the GUI. That is the most important information since we build SDKs around such information where we dont need to worry about URLs or any other information but the "Operation ID" is critical to find the function name among other things related to it.

## Describe the solution you'd like

Display the "Operation ID" in the GUI.

## Additional context

gz#7794<br><br><i>(related to <a href='https://stoplight.zendesk.com/agent/tickets/7794'>Zendesk ticket #7794</a>)</i>

**Comment by mnaumanali94** [comment]
Hey @yordis, we show the operation ID in case a title's missing. Is that a potential fix?

**Comment by yordis** [comment]
@mnaumanali94 no really, they are two different things used for two different reasons. The title is about a human-readable title, useful to PMs. While the operation ID is what engineers use to communicate and find the generated SDK operations.

**Comment by mnaumanali94** [comment]
@yordis Do you have any preference as to where to show these?

**Comment by yordis** [comment]
@mnaumanali94 no preferences, no.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
