### ISSUE TITLE
links in embedded pages not working

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#2133]
hi,

On our embedded API pages, I am seeing some links for the page navigation. It's being added by default. These inbuilt links are being shown on the GUI like below, once the user clicks on it "not found" error page is being rendered. How can we rectify or disable this inbuilt link on the pages?

![image](https://user-images.githubusercontent.com/66934062/165075638-4f9244e2-a634-40c6-b6de-d09b302619d2.png)

**Comment by mnaumanali94** [comment]
@smitabh84 Which version of elements dev portal are you using?

**Comment by smitabh84** [comment]
Where do I check it, Nauman?

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
