### ISSUE TITLE
OpenAPI Object with oneOf has no example in body 

### ISSUE THREAD

**Issue by lucianojs** [stoplightio/elements#2143]
When an OpenAPI object contains a oneOf, it fails to generate an example on the model view.

## Context

I don't send a valid sample API request because the body example is malformed.

## Current Behavior

When I have a OpenAPI like this:

```
openapi: 3.0.3
info:
  title: A minimal OpenAPI document
  version: 0.0.1
paths:
  /sample:
    put:
      requestBody:
        content:
          application/json:
            schema:
              properties:
                responsavel:
                  type: object
                  properties:
                    cnpj:
                      type: string
                      title: CNPJ
                      example: '00000000000191'
                    cpf:
                      type: string
                      title: CPF
                      example: '00000000191'
                  oneOf:
                    - required:
                        - cpf
                    - required:
                        - cnpj
      responses:
        '200':
          description: Updated
```

The object in example is empty

![localhost_8080_api_v1_index html (1)](https://user-images.githubusercontent.com/5367385/167972355-a3e03775-ffa9-4f12-95e1-62c5de76b21b.png)

## Expected Behavior

I'd expect the should show up as an example on the right, like:

```
{
  "responsavel": {
    "cnpj": "00000000000191",
  }
}
```

or 

```
{
  "responsavel": {
    "cpf": "00000000191"
  }
}
```

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by lucianojs** [comment]
Hi @AlexVarchuk, you are right again.

I supposed the samples would update when I changed the oneOf options and understood the not keyword.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
