### ISSUE TITLE
When using Try It or Send API Request, there is no formatting and indentation for response payload when it is big

### ISSUE THREAD

**Issue by remisbaima** [stoplightio/elements#2145]
## Context

Also the Elements UI gets super slow when payload is big.

## Current Behavior

![image](https://user-images.githubusercontent.com/1174143/168317110-4a614cdb-10bf-4d43-b24b-502429139025.png)

## Expected Behavior

The response payload would be formatted and indented to make it more readable. And also that the performance would be better for big payloads.

## Steps to Reproduce

1. set the Bearer token or not if your API does not expect one
2. click Send API Request
3. check the big response payload which needs multiple lines to be shown, but is shown in a single line with a lot of horizontal scrolling

## Environment

Using localhost in VS Code with "Live Server" extension: http://127.0.0.1:5500/reference/#/operations/list-features

```
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Elements in HTML</title>
  
    <script src="https://unpkg.com/@stoplight/elements/web-components.min.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/@stoplight/elements/styles.min.css">
  </head>
  <body>

    <elements-api
      apiDescriptionUrl="http://127.0.0.1:5500/my-api-full.v1.yaml"
      router="hash"
    />

  </body>
</html>
```
- Version used: https://unpkg.com/@stoplight/elements@7.5.18/styles.min.css
- Environment name and version (e.g. Chrome 39, node.js 5.4): Chrome Version 101.0.4951.64 (Official Build) (64-bit)
- Operating System and version (desktop or mobile): Desktop Windows 10
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
