### ISSUE TITLE
Credentials omitted when resolving external $ref

### ISSUE THREAD

**Issue by ocadoret** [stoplightio/elements#2151]
External $ref are fetch with `Credentials: omit`, resulting in error when the schema urls aren't public and require valid credentials. 

## Context
My api description is done in multiple yaml files using external $refs. I have a basic html integration with apiDescriptionUrl :
```
   <elements-api
      apiDescriptionUrl="./api.yaml"
      router="hash"
      layout="sidebar"
      tryItCredentialsPolicy="same-origin"
    />
```
All routes are protected, and you needed to be authenticated with sufficient rights to access the api documentation.

## Current Behavior
The html and root yaml files load fine, every other yaml file (external $refs) throw errors because the xhr requests doesn't include the credentials.
It seems to come from the [useBundleRefsIntoDocument](https://github.com/stoplightio/elements/blob/main/packages/elements-core/src/hooks/useBundleRefsIntoDocument.ts) hook, the $RefParser by default explicitly use `credentials: omit`.

## Expected Behavior
The xhr requests should include the credentials, just like the request to fetch the root yaml file.

## Possible Workaround/Solution
Hacky workaround : overwrite the window's `fetch` method to force the credentials to `same-origin` for every request.
Better solutions would be :
- give an option on elements-api to include credentials with $RefParser
- change default $RefParser behaviour to have browsers default credentials policy on fetches 

## Steps to Reproduce
1. Create an api with multiple yaml files and external $refs
2. Add authentication with access granted with a session cookie
3. Only the root yaml file is fetched, others raise HTTP auth errors

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by aleskovets** [comment]
Looks related https://github.com/stoplightio/elements/pull/2006

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
