### ISSUE TITLE
Update code samples, support typescript, add custom code samples

### ISSUE THREAD

**Issue by avin-kavish** [stoplightio/elements#2175]
I love your framework. I just need a couple of things for my project. Not sure if they can be done as is or it would require framework changes.

1. Current code samples to be updated and use modern language syntax. (Example, async/await for js)
2. Add TypeScript samples
3. Showcase using my own custom client library for making these requests.

Example,

```ts
  const client = MyApiClient('url')

  await client.getUser()
```

**Comment by ajrice6713** [comment]
+1 would be great to have custom code sample support. ReDoc and others support this functionality.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
