### ISSUE TITLE
Unable To Use "Stoplight Elements" In React Vite App - `require is not defined`

### ISSUE THREAD

**Issue by aerialist7** [stoplightio/elements#2216]
Hi Team,

we're using `<API/>` react component from `@stoplight/elements` in our Vite/React project.
But the app doesn't work in production - it fails with ```Uncaught ReferenceError: require is not defined``` error.

Sample: https://github.com/aerialist7/stoplight-elements-sample/tree/vite-react-component
To reproduce the issue just run `preview` command in my sample.

Could you please help us to fix it?

relates #2084
cc @lottamus

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
