### ISSUE TITLE
how to add API path links from a md file

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#2256]
<I have a static md file(workflow.md) which gives a workflow link to the user, I have added a few links but every time I update a new yaml file for the API reference. The id(marked in red) changes and the link breaks. 
Is there a better way to give internal links in an md file? Screenshot is attached for reference.

![image](https://user-images.githubusercontent.com/66934062/194260633-7a2f1fd6-acb1-4e1f-87c9-8296b102db7f.png)

Thanks.

**Comment by mnaumanali94** [comment]
@smitabh84 Can you explain a bit more as to what you mean by "update a new yaml file for the API reference"? Are you updating the existing file or creating a new one?

**Comment by smitabh84** [comment]
Hi Nauman, 

So if you see under references, we have one API reference yaml for each release. Once I import a new yaml file and add its address to the TOC, the links shown in the screenshot break due to the Id change in the link address (highlighted in the screenshot).

Please let me know if I could explain the issue clearly else I will try and add a video clip.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
