### ISSUE TITLE
404 error while rendering APIs

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#2257]
This is an intermittent issue but we are seeing it quite often now. 

Nutanix uses an embedded system to upload our APIs through Stoplight studio on nutanix.dev. Recently, when users click on any product name to launch the API details, a 404 error screen is shown. It goes off when the user refreshes the page.  As I pointed out earlier, it's an intermittent issue but happening quite frequently in the last few days.

**Comment by mnaumanali94** [comment]
@smitabh84 About two weeks ago we had some performance problems that have since been resolved. Are you still seeing this?

**Comment by smitabh84** [comment]
Hi Nauman,

I am not seeing it currently, but as I had mentioned it is an intermittent issue. I will keep a watch and update this thread if the 404 error is reported by customers again. Thanks for the update.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
