### ISSUE TITLE
Make it possible to set the server via the `Api` component

### ISSUE THREAD

**Issue by banool** [stoplightio/elements#2279]
Hi, you can see how I'm using the `Api` component of Stoplight elements here: https://github.com/aptos-labs/aptos-core/pull/5345/commits/de747256be53c99f2e2a91f6f479b91b8b940eb0.

The problem with this is because the spec explorer is embedded in a different site (see it at https://aptos.dev/nodes/aptos-api-spec#/), it shows the wrong site for "Live Server" / "API Base URL". Unfortunately the server I want to use cannot be derived from the site where the spec is hosted nor the server field in the spec. As such, I'd love to be able to specify the base URL when creating the `Api` component. As it is now, it doesn't seem to be possible.

Thanks!

**Comment by banool** [comment]
Hey just pinging this one to ensure it doesn't get reaped by a stale bot, I'd still love this feature. Or even some comment from the maintainers about whether they'd want this feature, then I could maybe look into adding it.

**Comment by mnaumanali94** [comment]
Hey @banool, if you add the API server to the OpenAPI spec, elements should show that. Is there something we are missing that prevents you from adding it to the OAS?

**Comment by banool** [comment]
In our case, anyone can run our API, it doesn't run from only a single URL. So it doesn't really make sense to have the server field set in our spec, since that would imply that the URL there is the authoritative location of the API when in reality we encourage anyone to run it (this is for a decentralized system).

**Comment by banool** [comment]
Hey @mnaumanali94 do you think this is a good idea to have, regardless of whether you have resources to implement it or not? I'm trying to decide whether to fix this with a hack or whether to possibly contribute this feature to stoplight.

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
