### ISSUE TITLE
Cannot set HTML title to the node title when using `StoplightProject` component

### ISSUE THREAD

**Issue by rafusel** [stoplightio/elements#2284]
## User Story Description

As a documentation viewer,

I want the title of the current tab (i.e. the HTML `<title>` tag) to be set to the node title of the page I am currently viewing,

so I can differentiate between which tabs have which documentation open when I have multiple tabs open.

This would be a nice quality of life improvement.

## Technical Detail
In the gatsby react example provided in this repo, the title of the page is set using using react-helmet but is always static. We can use the `useGetNodeContent` in our gatsby project to fetch the current node and set the title via react helmet to `node.title`. The issue is that the `useGetNodeContent` requires that we pass in the node slug from the current URL. The current URL is updated via a react router in the `StoplightProject` component, which means that any components in the component tree above `StoplightProject` don't know when the URL is updated and therefore can't change the node slug passed to `useGetNodeContent` to dynamically set the title. 

The only workarounds that I'm aware of would be polling the `window.location` object for changes to the pathname, or an approach similar to [this StackOverflow](https://stackoverflow.com/questions/5129386/how-to-detect-when-history-pushstate-and-history-replacestate-are-used) that fires browser events that can be listened to when `window.history.pushState/replaceState/go` are called. 

## Acceptance Criteria

- [ ] The react gatsby project is updated so that when we run it the title of the page is updated dynamically to the current node title
- [ ] If the node title is unavailable the current default value can be used

## Sprint Ready Checklist

- [ ] Acceptance criteria defined
- [ ] Team understands acceptance criteria
- [ ] Team has defined solution / steps to satisfy acceptance criteria
- [ ] Acceptance criteria is verifiable / testable
- [ ] External / 3rd Party dependencies identified

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
