### ISSUE TITLE
scrollbar problem

### ISSUE THREAD

**Issue by codeYhc** [stoplightio/elements#2291]
When the browser scroll bar scrolls, the sidebar and the navigation on the right will scroll up
https://support.stoplight.io/servlet/rtaImage?eid=500Do000001sC4C&feoid=00N3i00000DjRsl&refid=0EMDo000000HTLy

**Comment by chohmann** [comment]
Hello!

Our team recently took over the stewardship of the elements repo.

Due the volume of un-triaged issues that are pretty old and the time it would take us to get caught up on all of them, we kindly ask that you open up a new ticket if this is still an issue you're struggling with.

If you open a new issue please include:
- clear steps to reproduce that include example OAS specs, application setup, code, etc.
- the error or issue you are experiencing
- the expected behavior

We will be triaging any new tickets in a timely manner.

Thank you for understanding!
