### ISSUE TITLE
Request Body is not visible for some APIs

### ISSUE THREAD

**Issue by smitabh84** [stoplightio/elements#2485]
<(https://www.nutanix.dev/api_references/self-service/#/i71w8wdle0cdo-update-application)->
The Request Schema is not generated for this update request.
Same is the case for https://www.nutanix.dev/api_references/self-service/#/gp4hc75pamnny-create-application as well.

The yaml file updated for this product is here - 
[styx-swagger.json](https://github.com/stoplightio/elements/files/13711667/styx-swagger.json)

## Steps to Reproduce

1.
2.
3.
4.

## Environment

- Version used:
- Environment name and version (e.g. Chrome 39, node.js 5.4):
- Operating System and version (desktop or mobile):
- Link to your environment/workspace/project:

**Comment by chohmann** [comment]
@smitabh84 These endpoints are not showing the request body because you have not defined a format for the request body using the `consumes` property in the provided spec. This property needs to be defined in either to top level [Swagger object](https://spec.openapis.org/oas/v2.0#swagger-object) for the entire service, or at the individual [Operation objects](https://spec.openapis.org/oas/v2.0#operation-object). Once you define that, the request bodies will be shown in docs.
