### ISSUE TITLE
[Spike] figure out when the copy button breaks

### ISSUE THREAD

**Issue by marcelltoth** [stoplightio/elements#944]
Spike for #903

Spend at most half a day.

## Scope

Try to find a repro for #903 inside Mosaic's playground. If the problem doesn't occur there, find a stable repro in elements.

**Comment by marcelltoth** [comment]
@mallachari Would you summarise your findings here please?

**Comment by mallachari** [comment]
Yup, generally copy button breaks on first attempt and if there was something in the clipboard ahead it will remain. Second try replaces old content with new one. I was able to reproduce the same behaviour in mosaic playground. It looks that it's not up to mosaic and the problem is with `copy-to-clipboard` package itself. There were similar issues created in their repository (though already closed). Note that it works this way on linux, on mac it's fine.
What I've noticed is that using `copy` twice solves the issue so a quick fix could be one extra `copy` call in the `useClipboard` hook.  
Not sure if it's worth doing that as it's quite minor and rare issue. @marbemac what do you think?

**Comment by marcelltoth** [comment]
cc @marbemac

**Comment by marbemac** [comment]
Hmm - linux is ~10% of users on v2 saas. If switching to something like https://github.com/feross/clipboard-copy fixes the problems, then it's probably worth it since it's so simple to try another package. If not and this will be a more complicated fix, then I suggest we wait for folks to report it's an issue. What do you guys think?

**Comment by marcelltoth** [comment]
I'm OK with postponing it until someone reports it. 👍 Though note that I used to be able to - occasionally - reproduce on Windows.
